apiVersion: helm.cattle.io/v1
kind: HelmChartConfig

metadata:
  name: traefik
  namespace: kube-system

spec:
  failurePolicy: reinstall

  valuesContent: |-
    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443

   providers:
     kubernetesGateway:
       enabled: true
