apiVersion: gateway.networking.k8s.io/v1
kind: Gateway

metadata:
  name: traefik-gateway
  namespace: cert-manager

spec:
  gatewayClassName: traefik

  listeners:
    - name: websecure
      protocol: HTTPS
      port: 8443

      hostname: "*.cralyx.com"

      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: wildcard-cralyx-com-tls

      allowedRoutes:
        namespaces:
          from: All
