apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:5jjZBVNiWq1LvseYLtIEyLC8QJKj1Ph8eRM+fnoNZ9mgO21hQ3W1/4yOOsJA7u5htz0SyvI=,iv:ZXT/OcOvRA1d2jY+BB2QiXH+eFA77pSWotKVdXlFdpk=,tag:B0PJwxrdUaraH71qXPdHMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdU5OQ2pqK2lON1c4V1Bx
            Q1Z5USs0NDg4bWFwaFVsbkJyVmUzRUZhWEN3CnZUQVBSRFBlVVM5UXV2Z2NiN3lJ
            M21LNGd5OW9PRTJJWk9ZdFVIczFnV00KLS0tIDU3NlNCRG1CbXJud29BMytRbktm
            ZWhiYy9CNEZjczBiQTVwN2UzVzRZNkEK0fKwuS15plM0RvDFNCyTCf3ERWRruXvF
            gHtjBh4G7Fc4cUR4mph0ulffI9OWH/ULeSJ0YFeETWRH3k+noEIyhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n7qx554qx2h7tlascwe4nlsp0lh04pr5dlzwrx23vhzp7jada4tqny07rc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T11:44:33Z"
    mac: ENC[AES256_GCM,data:1C78jEcOKVcm8G8v8/0OxcjCni6Kbsf3wm9Wm8q7Ps0yZ29yzmBXQL9KP9Srn1M+zx+FglsBVH8OBChrtxAgwtf62IZJzoK9QtaR9JT5Gb4AIeF+6+tolXVSnlK6MCunyoRUBR+xogu4o/gmTo1z4O7SA6TQyglS5eelBRc71r8=,iv:NqiEdXX/L4w/NdyWAhK41zMTJtWatAJKX0uHj4m+2Dw=,tag:FiiZQmt+oJ3lUAa9BxsczA==,type:str]
    version: 3.13.1
